# Generated by Django 2.0.4 on 2018-07-30 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 21, 24, 34, 753718)),
        ),
    ]
