# Generated by Django 2.0.4 on 2018-09-19 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20180806_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 14, 37, 27, 220988)),
        ),
    ]
