# Generated by Django 2.0.4 on 2018-09-19 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20180919_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 15, 20, 10, 249845)),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
