# Generated by Django 2.0.4 on 2018-09-19 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20180919_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 16, 11, 28, 223232)),
        ),
    ]
